name: '${name}'
version: '${version}'
main: '${main}'
description: 'RSPlugin - ${name}'
api-version: '${api_version}'
depend: [ RSFramework, SDPoint, Vault, LuckPerms ]
softdepend: [ PlaceholderAPI ]
authors: [ '${author}' ]